changes

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -179,19 +179,19 @@ jobs:
       - name: Check for success file and create pull request
         run: |
           if [ -f curl-success.txt ]; then
-            echo "Curl command was successful, creating pull request..."
-            git config user.name "GitHub Actions"
-            git config user.email "actions@github.com"
-            git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/jdk3410/resume
-            git fetch origin master
-            git checkout -b merge-dev-to-master
-            git pull origin merge-dev-to-master
-            git merge --no-ff dev
-            git push origin merge-dev-to-master
-            echo $(gh pr create --repo jdk3410/resume --title "Merge dev into master" --body "This PR is automatically generated. Merging will happen automatically upon successful completion of all required checks and reviews." --base master --head merge-dev-to-master --label automerge -f)
-            else
-               echo "Curl command failed, not creating pull request."
-               exit 1
+             echo "Curl command was successful, creating pull request..."
+             git config user.name "GitHub Actions"
+             git config user.email "actions@github.com"
+             git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/jdk3410/resume
+             git fetch origin master
+             git checkout -b merge-dev-to-master
+             git pull --strategy-option theirs origin merge-dev-to-master
+             git merge --no-ff dev
+             git push origin merge-dev-to-master
+             echo $(gh pr create --repo jdk3410/resume --title "Merge dev into master" --body "This PR is automatically generated. Merging will happen automatically upon successful completion of all required checks and reviews." --base master --head merge-dev-to-master --label automerge -f)
+          else
+            echo "Curl command failed, not creating pull request."
+            exit 1
           fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
